-- Create suggestions table for student feedback
create table if not exists public.suggestions (
  id bigint generated by default as identity primary key,
  name text not null default 'ไม่ระบุชื่อ',
  type text not null,
  message text not null,
  created_at timestamptz not null default now()
);

-- Grant privileges to anon and authenticated users
grant all privileges on table public.suggestions to anon, authenticated, service_role;
