-- Create web_videos table to store activity videos
create table if not exists public.web_videos (
  id bigint generated by default as identity primary key,
  title text not null,
  video_url text not null,
  description text,
  created_at timestamptz not null default now()
);

-- Grant privileges to anon and authenticated users
grant all privileges on table public.web_videos to anon, authenticated, service_role;
